Adding input manager
Blindle/Arduino pull request #4
Opened 2017-09-23 04:06 UTC by EmaSuriano

# What's here? 

- Creation of MultiplexorHandler --> this class has the responsibility to communicate with the multiplexor, initializing the pins, applying delays, etc.
- Creation of InputManager --> this class has the responsibility of knowing from where to retrieve the input, in order to process it after.
- Creation of BarrelArranger --> this class has the responsibility to know what's the shape of a message to rotate a barrel, and also how to do it.
- A lot of code has been moved to this classes, so it looks a lot cleaner.

2017-09-23 15:37 UTC, santicanti requested changes

2017-09-23 15:37 UTC, santicanti commented on Arduino.ino
> +InputManager inputManager(1);
Que es el 1?

2017-09-23 15:37 UTC, santicanti commented on BarrelArranger.cpp
> +    int motorNumber = (int)word[2] - 48;
magic number

2017-09-23 15:37 UTC, santicanti commented on BarrelArranger.cpp
> +    _lastDirection = direction;
Adentro del if de arriba

2017-09-23 15:37 UTC, santicanti commented on BarrelArranger.cpp
> +    if (_lastDirection != direction)
Agregar comentario de esto

2017-09-23 15:37 UTC, santicanti commented on BarrelArranger.cpp
> +    if (direction == LEFT_DIRECTION)
Agregar comentario explicando esto

2017-09-23 15:37 UTC, santicanti commented on InputManager.cpp
> +    return words[_hardcodedWordIndex++];
return words[_hardcodedWordIndex++ % 3];  sino se va del array

2017-09-23 15:37 UTC, santicanti commented on MultiplexorHandler.cpp
> +    shiftOut(_dataPin, _clockPin, LSBFIRST, 0);
Extraer 0 a constante NO_DATA

2017-09-26 01:46 UTC, EmaSuriano commented on Arduino.ino
> +InputManager inputManager(1);
Es el modo, que esta declarado en el otro lado. No se me ocurrio otra forma de instanciarlo :/

2017-09-26 02:08 UTC, EmaSuriano commented on BarrelArranger.cpp
> +    if (_lastDirection != direction)
Erm para mi no hace falta, se entiende.

2017-09-26 14:03 UTC, santicanti commented on Arduino.ino
> +InputManager inputManager(1);
Pero qué es? Jajaja

2017-09-30 16:40 UTC, closed without merging